# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ManageLayers
                                 A QGIS plugin
 Sets defaukt vaklues for some attributes
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-11-01
        copyright            : (C) 2022 by Jiri Kalina
        email                : jiri.kalina.jr@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ManageLayers class from file ManageLayers.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .manage_layers import ManageLayers
    return ManageLayers(iface)
